### ISSUE TITLE
home page corrections

### ISSUE THREAD

**Issue by ChipNowacek** [amber-smalltalk/amber-website#1]
link in upper left points to Nico's github (and it doesn't render in Safari)

Also gotta update the copyright notice at the bottom of the page (Nico or Amber?)

And link on bottom of home page points to old github repo.

**Comment by ChipNowacek** [comment]
If you add the pages, I'll fix what I can.

**Comment by NicolasPetton** [comment]
The new website doesn't have this issue

**Comment by philippeback** [comment]
Where is the new website? No live yet I guess.

**Comment by NicolasPetton** [comment]
not yet, no.
In the meantime you can see it here: http://amber-smalltalk.github.com/amber-website/index.html

On Mar 10, 2013, at 5:35 PM, philippeback notifications@github.com wrote:

> Where is the new website? No live yet I guess.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Nicolas Petton
http://www.nicolas-petton.fr
