### ISSUE TITLE
Tutorial (ProfStef) fails to load http://amber-lang.net/amber/js/Web.js

### ISSUE THREAD

**Issue by jan-tomsa** [amber-smalltalk/amber-website#14]
When trying to open
http://amber-lang.net/learn.html
tutorial only shows "Loading..." message.

Apparently the page fails to load script http://amber-lang.net/amber/js/Web.js

According to Google Chrome Development Tools the page throws error:
Uncaught Error: Script error for: amber_core/Web

Firefox console:
Error: Script error for: amber_core/Web
http://requirejs.org/docs/errors.html#scripterror
(require.min.js:8)

**Comment by ghost** [comment]
Oh, yes. It needs to make it more up-to date, there's still an old version of amber used there but the profstef itself is newer so it awaits Web.js, not old name Canvas.js.

**Comment by ghost** [comment]
It seems it should be enough to update amber submodule in gh-pages branch to point to amber 0.12.6 release.

**Comment by hhzl** [comment]
This is amber 0.12.6 https://github.com/amber-smalltalk/amber/commit/fc74a60929f16ac78a659caf9764102a7cab1965

@herby  How do I update the submodule in gh-pages?

**Comment by ghost** [comment]
Just like any other time. Clone it, checkout gh-pages branch, get the submodules (git submodule update --init), go to subdir with submodule, update head to desired point, go to parent and commit (maybe git add will be needed before commit, maybe not). The parent reflects changes of the submodule head and includes it in the commit.

Hannes Hirzel notifications@github.comnapísal/a:

> Thisisamber0.12.6amber-smalltalk/amber@fc74a60HowdoIupdatethesubmoduleingh-pages?ReplytothisemaildirectlyorviewitonGitHub.
