### ISSUE TITLE
Nicolas is working on Amber as part of his work in the RMOD team.

### ISSUE THREAD

**Issue by ghost** [amber-smalltalk/amber-website#16]
@NicolasPetton Shouldn't it be changed to past tense?

**Comment by NicolasPetton** [comment]
Yes, it should :)

**Comment by hhzl** [comment]
Which page on http://amber-lang.net/ mentions this?

**Comment by mkroehnert** [comment]
The one you just posted.

**Comment by hhzl** [comment]
https://github.com/amber-smalltalk/amber-website/blob/gh-pages/_layouts/index.html

**Comment by hhzl** [comment]
Removed

```
Nicolas is working on Amber as part of his work in the RMOD team.

http://rmod.lille.inria.fr/
```

**Comment by hhzl** [comment]
## Page build failure

The page build failed with the following error:

The submodule registered for `./amber` could not be cloned. Make sure it's using https:// and that it's a public repo. For more information, see https://help.github.com/articles/page-build-failed-invalid-submodule.
