### ISSUE TITLE
The "Next Section" buttons point to different locations

### ISSUE THREAD

**Issue by adrian-castravete** [amber-smalltalk/amber-website#17]
In the _docs_ website there's a problem with the `Next section →` buttons. They point to `http://docs.amber-lang.net/overview/*` instead of `http://docs.amber-lang.net/*`.

For example on the **Loading Amber** page the next section link is
    http://docs.amber-lang.net/overview/creating-packages.html
whilst if I click in the list to the left it's
    http://docs.amber-lang.net/creating-packages.html

The latter works. :smiley:

**Comment by ghost** [comment]
This should be reported to docs' repo, not in website repo, as shown in main amber README. Closing.

**Comment by hhzl** [comment]
@adrian-castravete I have moved your issue to https://github.com/amber-smalltalk/amber-documentation/issues/25

You are very welcome to help to fix this...And you will learn a lot about Amber.
