### ISSUE TITLE
Change ``Copyright © 2011-2014``  to ``Copyright © 2011-2015``

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-website#20]
in the footer.

**Comment by ghost** [comment]
I read somewhere that these copyright messages should only add another year if that year brought some significant changes. Otherwise there is nothing to really copyright for that year.

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
I thought because of the release of Amber 0.14. Yes but it terms of the web site there is no significant change.
