### ISSUE TITLE
the top left "fork me on github" on the site is still going to nicolas github and looks bad on safari 

### ISSUE THREAD

**Issue by philippeback** [amber-smalltalk/amber-website#4]
Question mark on the top left of the browser window and goes to the wrong github project.
![Capture_d e cran_2013-03-06_a _17 53 48](https://f.cloud.github.com/assets/2128441/228383/bd628ddc-867e-11e2-861f-16f7282df390.png)

**Comment by philippeback** [comment]
Why closing this? It is not right yet. Or is this to be done in amber-site?

**Comment by NicolasPetton** [comment]
Same as the other one, it's not in the new website.

On Mar 10, 2013, at 5:34 PM, philippeback notifications@github.com wrote:

> Why closing this? It is not right yet. Or is this to be done in amber-site?
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Nicolas Petton
http://www.nicolas-petton.fr
