### ISSUE TITLE
Scrolling on Interactive ProfStef

### ISSUE THREAD

**Issue by NicolasPetton** [amber-smalltalk/amber-website#9]
The interactive ProfStef tutorial does not allow proper vertical scrolling (using Firefox and Chromium on Linux), such that the lesson on Numbers (4/24), for example, does not allow scrolling to see anything below 1 negated negated.

(from https://github.com/amber-smalltalk/amber/issues/439)

**Comment by semperos** [comment]
Thanks for transferring this and apologies for not looking through the amber-smalltalk repo's.

**Comment by tiye** [comment]
Same here on Macbook Chrome Canary. Oh, 5 months ago?

**Comment by NicolasPetton** [comment]
yeah, the website needs some love :)

**Comment by NicolasPetton** [comment]
Fixes! (finally)
